#theme: garth-jekyll-theme
theme: jekyll-theme-cayman
#theme: minima
mathjax: true
title: "Baseless Recursion"
description: "recurring on reality again & again"
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
future: true



collections:
        tech:
                output: true
